import { TableProps } from "../entities/types";

export const tableEasy: TableProps = [
  [
    { response: 4, validValues: [] },
    { response: 9, validValues: [] },
    { response: 6, validValues: [] },
    { response: 0, validValues: [] },
    { response: 7, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 8, validValues: [] },
    { response: 9, validValues: [] },
    { response: 0, validValues: [] },
    { response: 3, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 7, validValues: [] },
    { response: 5, validValues: [] },
    { response: 0, validValues: [] },
    { response: 8, validValues: [] },
    { response: 0, validValues: [] },
    { response: 2, validValues: [] },
    { response: 0, validValues: [] },
    { response: 1, validValues: [] },
    { response: 9, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 2, validValues: [] },
    { response: 5, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 1, validValues: [] },
    { response: 7, validValues: [] },
    { response: 2, validValues: [] },
    { response: 0, validValues: [] },
    { response: 4, validValues: [] },
    { response: 9, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 8, validValues: [] },
    { response: 0, validValues: [] },
    { response: 7, validValues: [] },
    { response: 0, validValues: [] },
    { response: 9, validValues: [] },
    { response: 0, validValues: [] },
    { response: 3, validValues: [] },
    { response: 6, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 8, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 7, validValues: [] },
    { response: 9, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 6, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 5, validValues: [] },
    { response: 4, validValues: [] },
    { response: 0, validValues: [] },
    { response: 3, validValues: [] },
    { response: 0, validValues: [] },
  ],
  [
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 0, validValues: [] },
    { response: 2, validValues: [] },
    { response: 8, validValues: [] },
    { response: 9, validValues: [] },
    { response: 1, validValues: [] },
    { response: 5, validValues: [] },
    { response: 6, validValues: [] },
  ],
];
